test .cache

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -19,24 +19,29 @@ publish:exchange-docker:
         paths:
           - "gears/**/*"
   before_script:
-#    - |-
-#      if [ ! -d ".cache/google-cloud-sdk.tar.gz" ]; then
-#      echo "not found"
-#      mkdir -p /usr/local/gcloud;
-#      curl -s \
-#      https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz > \
-#      .cache/google-cloud-sdk.tar.gz;
-#      tar -C /usr/local/gcloud -xf .cache/google-cloud-sdk.tar.gz;
-#      fi
-#    - tar -C .cache/gcloud -xf .cache/google-cloud-sdk.tar.gz;
-    - ls -al .cache/gcloud/google-cloud-sdk
     - |-
-      mkdir -p /usr/local/gcloud;
-      tar -C /usr/local/gcloud -xf .cache/google-cloud-sdk.tar.gz;
-      /usr/local/gcloud/google-cloud-sdk/install.sh \
+      if [ ! -d ".cache/gcloud/google-cloud-sdk/install.sh" ]; then
+      echo "not found"
+      mkdir -p .cache/gcloud;
+      curl -s \
+      https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz > \
+      .cache/google-cloud-sdk.tar.gz;
+      tar -C .cache/gcloud -xf .cache/google-cloud-sdk.tar.gz;
+      fi
+    - .cache/gcloud/google-cloud-sdk/install.sh \
       --path-update true \
       -q --rc-path /root/.bashrc &>/dev/null || {
           echo "Error occurred when installing gcloud SDK"; exit 1; }
+    - gcloud --version
+#    - tar -C .cache/gcloud -xf .cache/google-cloud-sdk.tar.gz;
+#    - ls -al .cache/gcloud/google-cloud-sdk
+#    - |-
+#      mkdir -p /usr/local/gcloud;
+#      tar -C /usr/local/gcloud -xf .cache/google-cloud-sdk.tar.gz;
+#      /usr/local/gcloud/google-cloud-sdk/install.sh \
+#      --path-update true \
+#      -q --rc-path /root/.bashrc &>/dev/null || {
+#          echo "Error occurred when installing gcloud SDK"; exit 1; }
 #    - |-
 #      if [ ! -d ".cache/google-cloud-sdk.tar.gz" ]; then
 #      echo "not found"
